In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
pd.set_option('display.float_format', '{:.5f}'.format)

Let X be the training data set, rows are samples and columns are samples

In [2]:
X = np.eye(4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Principal Components Analysis (PCA) is a linear transformation that attempts to create a lower dimensional form of some data while retaining maximum information (i.e maximise variance)

(suppose 100 dimensions but we want to squeeze out all the information in those 100 dimensions into 3 dimensions, maximising variance collects the most 'uniqueness' (i.e unique linear combinations i.e principal components) from 100 dimensions into 3 dimensions)

In [3]:
pca = PCA(n_components=X.shape[1])

In [4]:
print(f'PCA Transformed data \n\n {pca.fit_transform(X)}\n')
print(f'Variance explained ratio: \n\n {pca.explained_variance_ratio_}')

PCA Transformed data 

 [[-1.94283606e-17  7.76889138e-17  8.66025404e-01  5.55111512e-17]
 [ 8.16496581e-01  9.90037857e-17 -2.88675135e-01  5.55111512e-17]
 [-4.08248290e-01  7.07106781e-01 -2.88675135e-01  5.55111512e-17]
 [-4.08248290e-01 -7.07106781e-01 -2.88675135e-01  5.55111512e-17]]

Variance explained ratio: 

 [3.33333333e-01 3.33333333e-01 3.33333333e-01 4.10865055e-33]


Inspecting the variance explained, we can see that PC(1), PC(2) and PC(3) [principal component i] account for 33% of the variance in the data 

In [5]:
print(f'These are the eigen vectors computed (sorted by eigenvalues in descending order) for each component we set from X, i.e {pca.n_components_}')
pca.components_

These are the eigen vectors computed (sorted by eigenvalues in descending order) for each component we set from X, i.e 4


array([[ 3.92523115e-17,  8.16496581e-01, -4.08248290e-01,
        -4.08248290e-01],
       [-0.00000000e+00,  2.62681588e-16,  7.07106781e-01,
        -7.07106781e-01],
       [ 8.66025404e-01, -2.88675135e-01, -2.88675135e-01,
        -2.88675135e-01],
       [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
        -5.00000000e-01]])

In [6]:
print(f'These are the eigen values (sorted largest to smallest) for each component we set from X, i.e {pca.n_components_}')
pca.explained_variance_

These are the eigen values (sorted largest to smallest) for each component we set from X, i.e 4


array([3.33333333e-01, 3.33333333e-01, 3.33333333e-01, 4.10865055e-33])

In [7]:
print(f'SKLearn performs eigenvalue decomposition and sorts by desc e-val on e-vec matrix \nand transposes so each row is an e-vec \nDOES NOT NORMALIZE')
pca.transform(X)

SKLearn performs eigenvalue decomposition and sorts by desc e-val on e-vec matrix 
and transposes so each row is an e-vec 
DOES NOT NORMALIZE


array([[ 0.00000000e+00, -2.77555756e-17,  8.66025404e-01,
         1.11022302e-16],
       [ 8.16496581e-01,  2.22044605e-16, -2.88675135e-01,
        -2.77555756e-17],
       [-4.08248290e-01,  7.07106781e-01, -2.88675135e-01,
        -1.38777878e-16],
       [-4.08248290e-01, -7.07106781e-01, -2.88675135e-01,
        -5.55111512e-17]])

#### Check if fit_transform() is np.dot(X, pca.transform())

In [8]:
np.dot(X, pca.transform(X))

array([[ 0.00000000e+00, -2.77555756e-17,  8.66025404e-01,
         1.11022302e-16],
       [ 8.16496581e-01,  2.22044605e-16, -2.88675135e-01,
        -2.77555756e-17],
       [-4.08248290e-01,  7.07106781e-01, -2.88675135e-01,
        -1.38777878e-16],
       [-4.08248290e-01, -7.07106781e-01, -2.88675135e-01,
        -5.55111512e-17]])

#### Manually calculate pca

In [9]:
print(f'PCA class centers your data, but NO NORMALIZATION')
X_t = X - X.mean(axis=1).reshape(X.shape[0],1)
X_t

PCA class centers your data, but NO NORMALIZATION


array([[ 0.75, -0.25, -0.25, -0.25],
       [-0.25,  0.75, -0.25, -0.25],
       [-0.25, -0.25,  0.75, -0.25],
       [-0.25, -0.25, -0.25,  0.75]])

#### Eigen decomposition

In [10]:
S = X_t @ X_t.T / (X.shape[0]-1)
S

array([[ 0.25      , -0.08333333, -0.08333333, -0.08333333],
       [-0.08333333,  0.25      , -0.08333333, -0.08333333],
       [-0.08333333, -0.08333333,  0.25      , -0.08333333],
       [-0.08333333, -0.08333333, -0.08333333,  0.25      ]])

In [11]:
e_val, e_vecs = np.linalg.eig(S)
print(f'{e_val}\n\n')
print(f'{e_vecs.T}')

[3.33333333e-01 1.38777878e-17 3.33333333e-01 3.33333333e-01]


[[ 0.8660254  -0.28867513 -0.28867513 -0.28867513]
 [-0.5        -0.5        -0.5        -0.5       ]
 [-0.21575849  0.83906078 -0.14556019 -0.47774211]
 [ 0.08864522 -0.3447314  -0.52022854  0.77631472]]


In [12]:
idx = e_val.argsort()[::-1]
print(idx)

[3 0 2 1]


In [13]:
e_val_sorted = e_val[idx]
e_val_sorted

array([3.33333333e-01, 3.33333333e-01, 3.33333333e-01, 1.38777878e-17])

In [14]:
e_vecs_sorted = e_vecs[:,np.argsort(-e_val)]
e_vecs_sorted.T 

array([[ 0.8660254 , -0.28867513, -0.28867513, -0.28867513],
       [ 0.08864522, -0.3447314 , -0.52022854,  0.77631472],
       [-0.21575849,  0.83906078, -0.14556019, -0.47774211],
       [-0.5       , -0.5       , -0.5       , -0.5       ]])

In [15]:
(e_vecs_sorted.T @ X_t).T

array([[ 0.8660254 ,  0.08864522, -0.21575849,  0.        ],
       [-0.28867513, -0.3447314 ,  0.83906078,  0.        ],
       [-0.28867513, -0.52022854, -0.14556019,  0.        ],
       [-0.28867513,  0.77631472, -0.47774211,  0.        ]])